version: '2'
services:
  db:
    container_name: assignment1-db
    image: mcr.microsoft.com/azure-sql-edge
    ports:
      - "1433:1433"
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: SqlExpress!
  mvc:
    container_name: assignment1-mvc
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "5000:80"
      - "5001:443"
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Development